#!/bin/bash

######################################################################
# The script toolbox is created to backup and restore your
# Debian/Ubuntu OS (64bits).
#---------------------------------------------------------------------
# This is the **restore** script which invokes needed child scripts to
# complete the restore work.
#---------------------------------------------------------------------
# by pax (coolwinding@gmail.com) 150122
######################################################################

function notice() {
	cat <<EOF
**********************************************************************
Notice:
  1. Modify me at first, to make your OS happy!
  2. Restore from "${DATA_DIR}", and original files will be saved under "${P}/old/".
**********************************************************************
EOF
}

function usage() {
	cat <<EOF
Usage: xrestore [OPTIONS]...
  OPTIONS:
  -d DATA_DIR               Absolute data dir (default ${P}/data).
                              Put the files you want to restore here at first.
EOF
	exit
}

H=${USER}@${HOSTNAME}
T=$(date +"%Y%m%d%H%M%S")

W=`pwd`
echo ">>> work path: ${W}"
P=`dirname $(readlink -f $0)`
echo ">>> project path: ${P}"

cd $P

while getopts ":d:" OPTION
do
	case $OPTION in
		d ) DATA_DIR="$OPTARG";;
		* ) usage;;
	esac
done

if [ -z "$DATA_DIR" ]; then
	DATA_DIR="${P}/data"
fi

LOG_DIR="${P}/log"

mkdir -p ${LOG_DIR}

echo ">>> data path: ${DATA_DIR}"

. ./toolbox/utils

function main() {
	notice
	echo ">>>>>> Begin, please read and configure this script at first, or the OS may be broken!"

	echo "### step 1. configure network..."
	give_me_a_chance || exit
	#sudo ./toolbox/configure_network 'static' 'eth0' '172.28.130.51' '255.255.255.0' '172.28.130.1' '172.31.1.1'
	echo "skip it now! you can invoke it by hand"
	echo "### step 1. over..."

	echo "### step 2. configure language and locale..."
	give_me_a_chance || exit
	sudo ./toolbox/configure_language "en_US.UTF-8"
	echo "### step 2. over..."

	echo "### step 3. configure date and time..."
	give_me_a_chance || exit
	#sudo ./toolbox/configure_datetime '172.31.1.1'
	echo "skip it now! you can invoke it by hand"
	echo "### step 3. over..."

	echo "### step 4. configure apt source..."
	give_me_a_chance || exit
	sudo ./toolbox/configure_apt_sources "${DATA_DIR}/sources.list"
	echo "### step 4. over..."

	echo "### step 5. install packages..."
	give_me_a_chance || exit
	sudo ./toolbox/install_packages "${DATA_DIR}/packages"
	echo "### step 5. over..."

	echo "### step 6. configure dconf..."
	give_me_a_chance || exit
	./toolbox/configure_dconf "${DATA_DIR}/dconf"
	echo "### step 6. over..."

	echo "### step 7. do some other settings..."
	give_me_a_chance || exit
	echo "symlink sh to bash"
	sudo ln -sf /bin/bash /bin/sh
	echo "### step 7. over..."

	echo ">>>>>> All done! maybe you should restart your OS now"
}

# am i root?
who=$(whoami)
echo ">>> whoami: $who"

main 2>&1 | tee ${LOG_DIR}/restore_${H}_${T}.log

echo ">>> log path: ${LOG_DIR}"
